resolver: 'lts-17.9'

# Dev options
ghc-options:
  fregot: -freverse-errors

packages:
- '.'

extra-deps:
- './packages/pcre-simple'
- 'ansi-terminal-0.11'
- 'base16-bytestring-1.0.1.0'
- 'base64-bytestring-1.2.0.1'
- 'optparse-applicative-0.16.1.0'
- 'vector-0.12.2.0'
- git: https://github.com/fugue/goldplate.git
  commit: d799f3a88f50f79a080da9444853a7708d9b417f

nix:
  packages: ['zlib.dev', 'zlib.out']
