resolver: 'lts-19.12'

# Dev options
ghc-options:
  fregot: -freverse-errors

packages:
- '.'

extra-deps:
- './packages/pcre-simple'
- git: https://github.com/fugue/goldplate.git
  commit: 0ebf8fc353e518acf1f7eebcab3d733ed1031b1e

nix:
  packages: ['zlib.dev', 'zlib.out']
